### ISSUE TITLE
Typo in  RoosterTeeth.bundle/Contents/Code/__init__.py in the wip branch

### ISSUE THREAD

**Issue by dyuser** [meriko/RoosterTeeth.bundle#5]
There is a typo in the WIP branch which reads:
'url': 'http://funhaus.roosterteeth/show',
it should read:
'url': 'http://funhaus.roosterteeth.com/show',
Easy fix.

**Comment by meriko** [comment]
Yeah but it was fixed in the master branch. The WIP branch is to be deleted(since all changes are merged into master already)

So, please try/use the master branch instead
