### ISSUE TITLE
Can't watch new RWBY episodes

### ISSUE THREAD

**Issue by LINK1733** [meriko/RoosterTeeth.bundle#7]
I have a Rooster Teeth First account and am signed in with it but I can't watch the new RWBY episodes. I tried last week and this week and they both say "This channel is not responding" when I click on the new episode from the list of episodes. The episode that came out last week is working now though. 

EDIT: For clarification, I tried watching V4 E2 when it still needed a FIRST account to watch but now that its free I can watch it with no issues using this channel. But now V4 E3 is doing this issue.

**Comment by spaz926** [comment]
Check out Issue #6

**Comment by meriko** [comment]
Should be fixed in latest, please confirm(thanks @sander1 and @smilligan93)
